spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://159.75.255.32:3306/my_security?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 0906Zyh@

  redis:
    database: 0
    host: 159.75.255.32
    port: 6379
    password: 0906zyh@

mybatis-plus:
  configuration:
    cache-enabled: true

minio:
  endpoint: http://114.132.231.34:9000
  accessKey: pWIUVKNLUVAZ1Vm0
  secretKey: bT2zCgyDEvjxNe1a5DJwMdqmU6zzjYQA
#  bucketName: public